-- Generated by hyprmoncfg

hl.monitor({
  output = "desc:AU Optronics 0x683D",
  mode = "1920x1080@60.05",
  position = "10014x-1043",
  scale = 1.5,
  vrr = 0,
  sdr_min_luminance = 0.2,
  sdr_max_luminance = 80,
})

hl.workspace_rule({ workspace = "3", monitor = "desc:AU Optronics 0x683D" })
