-- Generated by hyprmoncfg

hl.monitor({
  output = "desc:AU Optronics 0x683D",
  mode = "1920x1080@60.05",
  position = "10014x-1043",
  scale = 1.5,
  vrr = 0,
  sdr_min_luminance = 0.2,
  sdr_max_luminance = 80,
})

hl.monitor({
  output = "desc:Lenovo Group Limited P27q-20 V90CXKKK",
  mode = "2560x1440@59.95",
  position = "10014x-2195",
  scale = 1.25,
  vrr = 0,
  sdr_min_luminance = 0.2,
  sdr_max_luminance = 80,
})

hl.monitor({
  output = "desc:Lenovo Group Limited P27q-20 V90CXKKL",
  mode = "2560x1440@59.95",
  position = "7966x-2195",
  scale = 1.25,
  vrr = 0,
  sdr_min_luminance = 0.2,
  sdr_max_luminance = 80,
})

hl.workspace_rule({ workspace = "1", monitor = "desc:Lenovo Group Limited P27q-20 V90CXKKL" })
hl.workspace_rule({ workspace = "2", monitor = "desc:Lenovo Group Limited P27q-20 V90CXKKK" })
hl.workspace_rule({ workspace = "3", monitor = "desc:AU Optronics 0x683D" })
