-- Generated by hyprmoncfg

hl.monitor({
  output = "desc:Seiko Epson Corporation EPSON PJ 0x01010101",
  mode = "1920x1200@59.95",
  position = "0x0",
  scale = 1.25,
  vrr = 0,
  sdr_min_luminance = 0.2,
  sdr_max_luminance = 80,
})
