-- Generated by hyprmoncfg

hl.monitor({
  output = "desc:AU Optronics 0x683D",
  mode = "1920x1080@60.05",
  position = "4283x840",
  scale = 1.5,
  vrr = 0,
  sdr_min_luminance = 0.2,
  sdr_max_luminance = 80,
})

hl.monitor({
  output = "desc:Seiko Epson Corporation EPSON PJ 0x01010101",
  mode = "1920x1200@59.95",
  position = "5563x0",
  scale = 2,
  vrr = 0,
  sdr_min_luminance = 0.2,
  sdr_max_luminance = 80,
  mirror = "desc:AU Optronics 0x683D",
})

hl.workspace_rule({ workspace = "3", monitor = "desc:AU Optronics 0x683D" })
