#on Error running GUI as root: https://wiki.archlinux.org/title/Xhost

###################
### MY PROGRAMS ###
###################

# See https://wiki.hypr.land/Configuring/Keywords/

$terminal = kitty
$fileManager = yazi
$editor = nvim
$menu = walker

#############################
### Ext. HYPRLAND CONFIG. ###
#############################

# See https://wiki.hypr.land/Configuring/Monitors/
source = ~/.config/hypr/monitors.conf

# See https://wiki.hypr.land/Configuring/Variables/#input
source = ~/.config/hypr/input.conf

# See https://wiki.hypr.land/Configuring/Keywords/
source = ~/.config/hypr/bindings.conf

# See https://wiki.hypr.land/Configuring/Variables/
source = ~/.config/hypr/looknfeel.conf

# See https://wiki.hypr.land/Configuring/Environment-variables/
source = ~/.config/hypr/envs.conf

source = ~/.config/hypr/autostart.conf

###################
### PERMISSIONS ###
###################

# See https://wiki.hypr.land/Configsearch replaceuring/Permissions/
# Please note permission changes here require a Hyprland restart and are not applied on-the-fly
# for security reasons

# ecosystem {
#   enforce_permissions = 1
# }

# permission = /usr/(bin|local/bin)/grim, screencopy, allow
# permission = /usr/(lib|libexec|lib64)/xdg-desktop-portal-hyprland, screencopy, allow
# permission = /usr/(bin|local/bin)/hyprpm, plugin, allow


##############################
### WINDOWS AND WORKSPACES ###
##############################

# See https://wiki.hypr.land/Configuring/Window-Rules/ for more
# See https://wiki.hypr.land/Configuring/Workspace-Rules/ for workspace rules

# Example windowrules that are useful

windowrule {
    # Ignore maximize requests from all apps. You'll probably like this.
    name = suppress-maximize-events
    match:class = .*

    suppress_event = maximize
}

windowrule {
    # Fix some dragging issues with XWayland
    name = fix-xwayland-drags
    match:class = ^$
    match:title = ^$
    match:xwayland = true
    match:float = true
    match:fullscreen = false
    match:pin = false

    no_focus = true
}

# Hyprland-run windowrule
windowrule {
    name = move-hyprland-run

    match:class = hyprland-run

    move = 20 monitor_h-120
    float = yes
}

# TouchScreen
input {
  touchdevice {
    output = eDP-1  # Replace $monitor0 with your desired monitor (e.g., $monitor1, HDMI-A-1)
    transform = 0       # Adjust if needed for rotation
  }
  tablet {
    output = eDP-1  # Applies to pen input if used
    transform = 0
  }
}   
