wallpaper {
    monitor = eDP-1
    path = ~/.config/bulb.jpeg
    fit_mode = cover
}
wallpaper {
    monitor = DP-1
    path = ~/.config/bulb.jpeg
    fit_mode = cover
}
wallpaper {
    monitor = DP-2
    path = ~/.config/bulb.jpeg
    fit_mode = cover
}
