-- Generated by Antigravity
-- This script dynamically reads monitors.conf and translates it into lua hl.monitor calls

local conf_path = os.getenv("HOME") .. "/.config/hypr/monitors.conf"
local file = io.open(conf_path, "r")

if file then
    for line in file:lines() do
        -- Skip empty lines and comments
        local stripped = line:match("^%s*(.-)%s*$")
        if stripped ~= "" and not stripped:match("^#") then
            -- Match monitor=...
            local args_str = stripped:match("^monitor%s*=%s*(.+)")
            if args_str then
                local parts = {}
                for part in string.gmatch(args_str, "([^,]+)") do
                    table.insert(parts, part)
                end
                
                if #parts >= 4 then
                    local mon = {
                        output = parts[1]:match("^%s*(.-)%s*$"),
                        mode = parts[2]:match("^%s*(.-)%s*$"),
                        position = parts[3]:match("^%s*(.-)%s*$"),
                        scale = parts[4]:match("^%s*(.-)%s*$")
                    }
                    
                    local i = 5
                    while i <= #parts do
                        local key = parts[i]:match("^%s*(.-)%s*$")
                        local next_val = nil
                        if i + 1 <= #parts then
                            next_val = parts[i+1]:match("^%s*(.-)%s*$")
                        end
                        
                        if next_val and tonumber(next_val) then
                            mon[key] = tonumber(next_val)
                            i = i + 2
                        elseif next_val == "true" or next_val == "false" then
                            mon[key] = (next_val == "true")
                            i = i + 2
                        else
                            mon[key] = true
                            i = i + 1
                        end
                    end
                    
                    hl.monitor(mon)
                end
            end
        end
    end
    file:close()
else
    print("Warning: Could not open " .. conf_path)
end
