-- Generated by nwg-displays on 2026-10-06 at 13:32:23. Do not edit manually.

hl.monitor({
    output = "eDP-1",
    mode = "1920x1080@60.05",
    position = "4283x840",
    scale = 1.5,
    vrr = 0
})
hl.monitor({
    output = "DP-2",
    mode = "0x0@60.0",
    position = "5563x0",
    scale = 1.0,
    mirror = "eDP-1",
    vrr = 0
})
