[opener]
edit = [
  { run = "nvim \"$@\"", block = true, for = "unix" },
]
play = [
  { run = "mpv \"$@\"", orphan = true, for = "unix" },
]
open = [
  { run = "kde-open \"$@\"", desc = "open" },
]
xournalpp = [
  { run = "xournalpp \"$@\"", orphan = true, desc = "xournal++" },
]
browser = [
  { run = "brave \"$@\"", desc = "browser" },
]
firefox = [
  { run = "firefox \"$@\"", orphan = true, desc = "firefox" },
]

[open]
prepend_rules = [
  { url = "*.html", use = [ "browser", "edit" ] },
  { url = "*.pdf", use = [ "firefox","xournalpp", "browser" ] },
  { url = "*.tex", use = [ "edit" ] },
]
